### ISSUE TITLE
Reference implmentation?

### ISSUE THREAD

**Issue by davidNHK** [ota-meshi/eslint-plugin-node-dependencies#33]
**Motivation**
I saw you have new repo for linting package.json and that kind of duplicated work to  https://npmpackagejsonlint.org/

but of course it would much better if we can do anything with just eslint may be we can refer to existing work and take some rules to eslint here.

**Description**
E.X prefer-absolute-version was one of rules i always use

**Examples**

```js
/* ✓ GOOD */
var foo = /regex/

/* ✗ BAD */
var foo = /regex/
```

**Comment by ota-meshi** [comment]
Thank you for posting this issue.

I think it's good to add a `prefer-absolute-version` rule to this plugin.

I'm not sure if all the rules provided by npm-package-json-lint should be added in this plugin. We need to check the rules one by one.
If you have a list of rules that you would like to add with this plugin, please provide it.

If you want to integrate npm-package-json-lint with ESLint, I think it's better to create another eslint-plugin.

**Comment by davidNHK** [comment]
FYR

'prefer-absolute-version-dependencies': 'error',
'prefer-absolute-version-devDependencies': 'error',
'require-engines': 'error',
'require-license': 'error',
'require-repository': 'error',
'require-version': 'error',
‘valid-values-license': ['error', ['MIT', 'UNLICENSED']]

I only use rules above in my project

**Comment by ota-meshi** [comment]
Thank you for listing rules.
I don't want to add any rules other than prefer-absolute-version to this plugin as they have nothing to do with dependencies.

Perhaps those rules can be checked in JSON Schema, so I think you can be checked using [eslint-plugin-json-schema-validator](https://github.com/ota-meshi/eslint-plugin-json-schema-validator).

**Comment by davidNHK** [comment]
@ota-meshi Thanks for make our life more easily ! 

As you suggested, here is my example integration of json-schema-validator

```
{
      extends: [
        'plugin:jsonc/prettier',
        'plugin:json-schema-validator/recommended',
      ],
      files: ['*.json'],
      parser: require.resolve('jsonc-eslint-parser'),
      rules: {
        'json-schema-validator/no-invalid': [
          'error',
          {
            schemas: [
              {
                fileMatch: ['package.json'],
                schema: {
                  $schema: 'https://json-schema.org/draft/2020-12/schema',
                  properties: {
                    engines: {
                      properties: {
                        node: {
                          const: '>=16',
                          type: 'string',
                        },
                        yarn: {
                          const: 'Use npm',
                          type: 'string',
                        },
                      },
                      required: ['node', 'yarn'],
                      type: 'object',
                    },
                    license: {
                      enum: ['MIT', 'UNLICENSED'],
                      type: 'string',
                    },
                    repository: {
                      oneOf: [
                        {
                          properties: {
                            directory: { type: 'string' },
                            type: { const: 'git', type: 'string' },
                            url: {
                              type: 'string',
                            },
                          },
                          required: ['url', 'type', 'directory'],
                          type: 'object',
                        },
                        {
                          type: 'string',
                        },
                      ],
                    },
                    version: {
                      type: 'string',
                    },
                  },

                  required: ['engines', 'version', 'license'],
                },
              },
            ],
          },
        ],
        'jsonc/sort-keys': 'error',
      },
    }
```

**Comment by ota-meshi** [comment]
I've added some rules inspired by npm-package-json-lint.
If you have other rules that you would like us to add, please open an issue separately.
