### ISSUE TITLE
Document it could be very slow for large projects due to `spawnSync`

### ISSUE THREAD

**Issue by JounQin** [ota-meshi/eslint-plugin-node-dependencies#54]
**Description**

https://github.com/1stG/configs/runs/7143403309?check_suite_focus=true#step:6:44

It is causing OOM on GitHub Action.

And also it could be improved by using [`synckit`](https://github.com/un-ts/synckit).

**Comment by ota-meshi** [comment]
> And also it could be improved by using synckit.

That's good to know! It's worth trying.

**Comment by JounQin** [comment]
A related package https://github.com/sindresorhus/package-json can also used to replace spawning `npm` cli.

**Comment by ota-meshi** [comment]
Thank you for letting me know! I will also try that package.
